#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 21 10:20:48 2020

@author: 
"""

from utils.mnistutil import MNISTUitl
from utils.sliceutil import Slice
from keras.models import load_model
import numpy as np
def jaccard_similarity(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection) / union
#In[]Module Load
module0=load_model('module0.h5')
module1=load_model('module1.h5')
module2=load_model('module2.h5')
module3=load_model('module3.h5')
module4=load_model('module4.h5')
module5=load_model('module5.h5')
module6=load_model('module6.h5')
module7=load_model('module7.h5')
module8=load_model('module8.h5')
module9=load_model('module9.h5')
#In[]: List formation
w1,b1 = module0.layers[1].get_weights()
w2,b2 = module0.layers[2].get_weights()
w3,b3 = module0.layers[3].get_weights()
w4,b4 = module0.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module0=np.concatenate((w1a,w2a))
w_module0=np.concatenate((w_module0,w3a))
w_module0=np.concatenate((w_module0,w4a))
#In[]: List formation
#In[]: List formation
w1,b1 = module1.layers[1].get_weights()
w2,b2 = module1.layers[2].get_weights()
w3,b3 = module1.layers[3].get_weights()
w4,b4 = module1.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module1=np.concatenate((w1a,w2a))
w_module1=np.concatenate((w_module1,w3a))
w_module1=np.concatenate((w_module1,w4a))

w1,b1 = module2.layers[1].get_weights()
w2,b2 = module2.layers[2].get_weights()
w3,b3 = module2.layers[3].get_weights()
w4,b4 = module2.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module2=np.concatenate((w1a,w2a))
w_module2=np.concatenate((w_module2,w3a))
w_module2=np.concatenate((w_module2,w4a))

w1,b1 = module3.layers[1].get_weights()
w2,b2 = module3.layers[2].get_weights()
w3,b3 = module3.layers[3].get_weights()
w4,b4 = module3.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module3=np.concatenate((w1a,w2a))
w_module3=np.concatenate((w_module3,w3a))
w_module3=np.concatenate((w_module3,w4a))

w1,b1 = module4.layers[1].get_weights()
w2,b2 = module4.layers[2].get_weights()
w3,b3 = module4.layers[3].get_weights()
w4,b4 = module4.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module4=np.concatenate((w1a,w2a))
w_module4=np.concatenate((w_module4,w3a))
w_module4=np.concatenate((w_module4,w4a))

w1,b1 = module5.layers[1].get_weights()
w2,b2 = module5.layers[2].get_weights()
w3,b3 = module5.layers[3].get_weights()
w4,b4 = module5.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module5=np.concatenate((w1a,w2a))
w_module5=np.concatenate((w_module5,w3a))
w_module5=np.concatenate((w_module5,w4a))

w1,b1 = module6.layers[1].get_weights()
w2,b2 = module6.layers[2].get_weights()
w3,b3 = module6.layers[3].get_weights()
w4,b4 = module6.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module6=np.concatenate((w1a,w2a))
w_module6=np.concatenate((w_module6,w3a))
w_module6=np.concatenate((w_module6,w4a))

w1,b1 = module7.layers[1].get_weights()
w2,b2 = module7.layers[2].get_weights()
w3,b3 = module7.layers[3].get_weights()
w4,b4 = module7.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module7=np.concatenate((w1a,w2a))
w_module7=np.concatenate((w_module7,w3a))
w_module7=np.concatenate((w_module7,w4a))

w1,b1 = module8.layers[1].get_weights()
w2,b2 = module8.layers[2].get_weights()
w3,b3 = module8.layers[3].get_weights()
w4,b4 = module8.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module8=np.concatenate((w1a,w2a))
w_module8=np.concatenate((w_module8,w3a))
w_module8=np.concatenate((w_module8,w4a))

w1,b1 = module9.layers[1].get_weights()
w2,b2 = module9.layers[2].get_weights()
w3,b3 = module9.layers[3].get_weights()
w4,b4 = module9.layers[4].get_weights()
w1a=w1.flatten()
w2a=w2.flatten()
w3a=w3.flatten()
w4a=w4.flatten()
w1a=np.array(w1a)
w2a=np.array(w2a)
w3a=np.array(w3a)
w4a=np.array(w4a)
w_module9=np.concatenate((w1a,w2a))
w_module9=np.concatenate((w_module9,w3a))
w_module9=np.concatenate((w_module9,w4a))
#In[]: Jaccard similarities
w_append=[]
w_append.append(w_module0)
w_append.append(w_module1)
w_append.append(w_module2)
w_append.append(w_module3)
w_append.append(w_module4)
w_append.append(w_module5)
w_append.append(w_module6)
w_append.append(w_module7)
w_append.append(w_module8)
w_append.append(w_module9)
index=[0,1,2,3,4,5,6,7,8,9]
index1=[0,1,2,3,4,5,6,7,8,9]
jaccard_index=[]
for i in index:
    for j in index1:
        if(i!=j):
            temp=jaccard_similarity(w_append[i],w_append[j])
            jaccard_index.append(temp)
JI=np.mean(jaccard_index)
print('mean jaccard index: '+str(round(JI, 2)))